import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import dbConnect from "@/dbConnect/mongo";
import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "./context/cartContext";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-50 text-gray-900 antialiased dark:bg-gray-900 dark:text-gray-100`}
      >
        <Toaster position="top-center" reverseOrder={false} />
        <SessionProvider>
          <CartProvider>
            <Header />
            {children}
          </CartProvider>
        </SessionProvider>
        <Footer />
      </body>
    </html>
  );
}
